version: '2'
services:
  web:
    build: .docker/web
    ports:
      - "80:80"
    environment:
      XDEBUG_CONFIG: remote_host=172.19.0.1
    volumes:
      - ./build/dmaster:/var/www/html:z
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=blablablaroot
      - MYSQL_DATABASE=drupal
      - MYSQL_CIVI_DB=civi
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=DbDevPw
  buildkit:
    build: .docker/buildkit
    volumes:
      - ./build:/opt/buildkit/build:z
